services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    hostname: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: ./api/
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PORT: 8080
  smtp:
    image: namshi/smtp
    container_name: smtp_relay
    restart: always
    ports:
     - "25:25"
    environment:
        - RELAY_NETWORKS=192.168.0.0/24:10.0.0.0/16
        - RELAY_DOMAINS=<gmail.com>:<lll.kpi.ua>:<ukr.net>
        - GMAIL_USER=${EMAIL_ADDRESS}
        - GMAIL_PASSWORD=${EMAIL_PASSWORD}